spring:
  profiles:
    active: dev
  application:
    name: 'user-service-api'
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI}
eureka:
    client:
        serviceUrl:
          defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}