spring:
  profiles:
    active: dev
  application:
    name: 'order-service-api'
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI:http://localhost:8888}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}