spring:
  application:
    name: 'helpdesk-bff'
  profiles:
    active: dev
  cloud:
    config:
      uri: 'config-server'
eureka:
  client:
    serviceUrl:
      fetch-registry: true
      register-with-eureka: true
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}