spring:
  application:
    name: 'helpdesk-bff'
  profiles:
    active: dev
  cloud:
    config:
      uri: 'config-server'
eureka:
  client:
    serviceUrl:
      fetch-registry: true
      register-with-eureka: true
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
springdoc:
  openapi:
    title: 'BFF Helpdesk API'
    description: 'Component responsible for aggregating the microservices of the Helpdesk system'
    version: '1.0.0'
server:
  port: ${PORT:0}
jwt.secret: 'nkKyXiPxGUTa/sdQDAkMKnoYX0nIFzjYGO8tBisYkN3VxGcgLqZtMBUnqPcEzqAKF+rH8Y/KgSmBXr4NA8RxrDosLafxs2eEtqx0CszlbLE='