spring:
  application:
    name: 'config-server'
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: ${CONFIG_SERVER_URI:https://github.com/gkl3in/help-desk-configs}
          username: ${CONFIG_SERVER_USERNAME}
          password: ${CONFIG_SERVER_PASSWORD}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
server:
  port: ${PORT:8888}